// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA89BkFUahbLxR89NtUW6w2LAC_K-643xY',
    appId: '1:869222114879:web:a1d058f0bb68e17436ba8a',
    messagingSenderId: '869222114879',
    projectId: 'gawla-19',
    authDomain: 'gawla-19.firebaseapp.com',
    storageBucket: 'gawla-19.firebasestorage.app',
    measurementId: 'G-H0JLHJHB0R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCSNI8iEzKZUu48ExXVaJJREa-mTeJ_Ic',
    appId: '1:869222114879:android:25cc6465124c2dcf36ba8a',
    messagingSenderId: '869222114879',
    projectId: 'gawla-19',
    storageBucket: 'gawla-19.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7JpXDCYer1IbumWwBp_iHJVgYRs5HRbM',
    appId: '1:869222114879:ios:0dc9fb8d212924e336ba8a',
    messagingSenderId: '869222114879',
    projectId: 'gawla-19',
    storageBucket: 'gawla-19.firebasestorage.app',
    iosBundleId: 'com.elesawy.gawlaApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7JpXDCYer1IbumWwBp_iHJVgYRs5HRbM',
    appId: '1:869222114879:ios:0dc9fb8d212924e336ba8a',
    messagingSenderId: '869222114879',
    projectId: 'gawla-19',
    storageBucket: 'gawla-19.firebasestorage.app',
    iosBundleId: 'com.elesawy.gawlaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA89BkFUahbLxR89NtUW6w2LAC_K-643xY',
    appId: '1:869222114879:web:414ea52db8008c6036ba8a',
    messagingSenderId: '869222114879',
    projectId: 'gawla-19',
    authDomain: 'gawla-19.firebaseapp.com',
    storageBucket: 'gawla-19.firebasestorage.app',
    measurementId: 'G-MFKP302TFH',
  );
}
